name: label-sponsors

on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  label:
    name: Add Sponsor Labels
    runs-on: ubuntu-latest
    steps:
      - uses: ueberdosis/sponsor-action@v1.0-alpha
        with:
          label: sponsor ðŸ’–
          github_token: ${{ secrets.GITHUB_TOKEN }}

